name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main


jobs:

  build:

    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Install dependencies for windows
        if: ${{ matrix.os == 'windows-latest'}}  
        run: cargo install --path .

      - name: Install dependencies for others
        if: ${{ matrix.os != 'windows-latest'}}  
        run: cargo build   

      - name: Test
        run: |
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cargo build --release